@baseUrl = http://localhost:8000/api
@groupId = 1
@questionId = 1
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5oY3V0bzc3N0BnbWFpbC5jb20iLCJpYXQiOjE3NzAwMTk4MTEsImV4cCI6MTc3MDYyNDYxMX0.nN8SIqLE9LPMIZf0Ut-RMfMw27wmx7iExjMGxFfEV7GnlMg6OejzLCGbqTxg6Q1Y4osXwek6pvThDlgq7wt7Rg

### Get all questions (Paginated)
GET {{baseUrl}}/questions?page=1&size=10
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get a specific question by ID
GET {{baseUrl}}/questions/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Create a new SELECTION Question
# Note: Ensure groupId refers to a group of type SELECTION
POST {{baseUrl}}/questionGroups/{{groupId}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "What is the capital of France?",
  "explanation": "Paris is the capital and most populous city of France.",
  "questionOptions": [
    {
      "content": "Berlin",
      "isCorrect": false
    },
    {
      "content": "London",
      "isCorrect": false
    },
    {
      "content": "Paris",
      "isCorrect": true
    },
    {
      "content": "Madrid",
      "isCorrect": false
    }
  ]
}

### Create a INPUT Question (Gap Fill)
# Note: Ensure groupId refers to a group of type INPUT
POST {{baseUrl}}/questionGroups/{{groupId}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "The capital of France is [blank].",
  "explanation": "Because you're supposed to know this!",
  "correctAnswers": ["Paris"],
  "questionOptions": []
}

### Update an existing Question
PUT {{baseUrl}}/questions/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "What is the capital of France? (Updated)",
  "explanation": "Updated explanation",
  "questionOptions": [
    {
      "content": "Berlin",
      "isCorrect": false
    },
    {
      "content": "Paris",
      "isCorrect": true
    },
    {
      "content": "Lyon",
      "isCorrect": false
    }
  ]
}

### Delete a Question
DELETE {{baseUrl}}/questions/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Question Group by ID
GET {{baseUrl}}/questionGroups/{{groupId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
